# -*- coding: utf-8 -*-
"""Regenerate the open-items register inside docs/17-execution-ledger.md.

    python3 scripts/docs/open-items.py [--check]     (or: pnpm docs:open-items)

WHY THIS IS GENERATED. Every packet leaves judgements behind, and they are
recorded where they belong — in the packet's own section of
20-packet-review-log.md, beside the work that produced them. That is the right
home for the reasoning and the wrong shape for the question "what is still
waiting on me". After eight packets the answer to that question is spread over
sixteen tables, and an item nobody re-reads is an item that has been forgotten
whether or not it was written down.

A hand-maintained index would answer it and then drift, which is worse than not
having one: a stale register is read as complete. So the ledger — the file that
already owns "what is next" — carries a generated view, and the review log stays
the single source of truth. Editing the block by hand is pointless; the next run
overwrites it.

`--check` exits non-zero when the block is out of date, so CI can fail a commit
that closes an item in the log without refreshing the register.

Statuses collected: `open` (needs a decision) and `**needs you**` (needs the
maintainer specifically). `carried` is deliberate and dormant, `resolved` is
settled — neither is waiting on anyone, so neither appears here.
"""

import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LOG = os.path.join(ROOT, "docs", "20-packet-review-log.md")
LEDGER = os.path.join(ROOT, "docs", "17-execution-ledger.md")

BEGIN = "<!-- BEGIN:open-items -->"
END = "<!-- END:open-items -->"

WAITING = {"open": "open", "**needs you**": "needs you"}


def cells(line):
    """Split a markdown table row, respecting `\\|` inside a cell.

    A naive split on "|" turns one row carrying a shell pipe — say a `curl …
    | grep …` command — into five cells, and the row is then silently dropped
    for having the wrong shape. The item stays out of the register and nobody
    notices, which is the exact failure this register exists to prevent.
    """
    body = line.strip().strip("|")
    return [cell.replace("\\|", "|").strip() for cell in re.split(r"(?<!\\)\|", body)]


def headline(text):
    """The claim, not the argument — the register links to the full entry."""
    bold = re.match(r"\*\*(.+?)\*\*", text)
    if bold:
        return bold.group(1).rstrip(".")
    sentence = re.split(r"(?<=[.؟?])\s", text)[0]
    return sentence.rstrip(".") if len(sentence) <= 160 else sentence[:157] + "…"


def collect():
    section, rows = None, []
    for line in io.open(LOG, encoding="utf-8"):
        if line.startswith("## "):
            section = line[3:].strip()
            continue
        if not line.startswith("|") or section is None:
            continue
        parts = cells(line)
        if len(parts) != 4 or set(parts[0]) <= set("-: "):
            continue
        identifier, what, kind, status = parts
        if status.lower() not in WAITING:
            continue
        rows.append((section, identifier, headline(what), kind, WAITING[status.lower()]))
    return rows


def render(rows):
    waiting = [row for row in rows if row[4] == "needs you"]
    open_rows = [row for row in rows if row[4] == "open"]

    out = [
        BEGIN,
        "",
        "Generated by `pnpm docs:open-items` from"
        " [`20-packet-review-log.md`](20-packet-review-log.md). Do not edit by hand —"
        " edit the entry in the review log and re-run.",
        "",
        "### Waiting on the maintainer",
        "",
        "Nothing below is a defect. Each is a decision, a fact or a permission only"
        " you can supply, and each blocks something.",
        "",
        "| Where | # | What | Kind |",
        "| ----- | - | ---- | ---- |",
    ]
    for section, identifier, what, kind, _ in waiting:
        out.append("| %s | %s | %s | %s |" % (section, identifier, what, kind))
    if not waiting:
        out.append("| — | — | Nothing is waiting on you. | — |")

    out += [
        "",
        "### Open — decided when it next matters",
        "",
        "| Where | # | What | Kind |",
        "| ----- | - | ---- | ---- |",
    ]
    for section, identifier, what, kind, _ in open_rows:
        out.append("| %s | %s | %s | %s |" % (section, identifier, what, kind))
    if not open_rows:
        out.append("| — | — | Nothing open. | — |")

    out += [
        "",
        "**Totals:** %d waiting on the maintainer, %d open."
        % (len(waiting), len(open_rows)),
        "",
        END,
    ]
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    block = render(collect())
    ledger = io.open(LEDGER, encoding="utf-8").read()

    if BEGIN not in ledger or END not in ledger:
        sys.exit("Markers %s / %s are missing from the ledger." % (BEGIN, END))

    start = ledger.index(BEGIN)
    stop = ledger.index(END) + len(END)
    updated = ledger[:start] + block + ledger[stop:]

    # Compared with whitespace collapsed. Prettier pads markdown table columns
    # to align them, so a byte-for-byte check would call a freshly generated
    # register stale the moment the formatter touched the file — and a check
    # that cries wolf gets switched off.
    def normalised(text):
        block = text[text.index(BEGIN) : text.index(END)]
        block = re.sub(r"-{2,}", "-", block)
        return re.sub(r"\s+", " ", block)

    if normalised(updated) == normalised(ledger):
        print("open-items register is up to date")
        return
    if check:
        sys.exit("open-items register is stale — run `pnpm docs:open-items`")
    io.open(LEDGER, "w", encoding="utf-8").write(updated)
    print("open-items register rewritten")


if __name__ == "__main__":
    main()
